/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.haila.frame;

import br.com.haila.objeto.Aluno;
import br.com.haila.objeto.Nota;
import br.com.haila.objeto.TipoAvaliacao;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class Principal extends javax.swing.JFrame {

    Aluno a;
    /**
     * Creates new form Principal
     */
       
    public Principal() {
        JComboBox combobox = new JComboBox();
        combobox.addItem("prova");
        combobox.addItem("trabalho");
        combobox.addItem("seminário");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLTitulo = new javax.swing.JLabel();
        jPNotas = new javax.swing.JPanel();
        jTFN1 = new javax.swing.JTextField();
        jTFN2 = new javax.swing.JTextField();
        jTFN3 = new javax.swing.JTextField();
        jTFN4 = new javax.swing.JTextField();
        jLNotas = new javax.swing.JLabel();
        jBCalcular = new javax.swing.JButton();
        jLN1 = new javax.swing.JLabel();
        jLN2 = new javax.swing.JLabel();
        jLaN3 = new javax.swing.JLabel();
        jLN4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLNomeDisciplina = new javax.swing.JLabel();
        jTFNomeDisciplina = new javax.swing.JTextField();
        jCDisciplina = new javax.swing.JComboBox<>();
        jPAluno = new javax.swing.JPanel();
        jLAluno = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jTFMatricula = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();
        jLMatricula = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(153, 0, 102));
        jLTitulo.setText("Calculo de Média");

        jPNotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTFN1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTFN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFN1ActionPerformed(evt);
            }
        });

        jTFN2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTFN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFN2ActionPerformed(evt);
            }
        });

        jTFN3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTFN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFN3ActionPerformed(evt);
            }
        });

        jTFN4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTFN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFN4ActionPerformed(evt);
            }
        });

        jLNotas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLNotas.setText("Notas");

        jBCalcular.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBCalcular.setText("Calcular");
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        jLN1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLN1.setText("N1");

        jLN2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLN2.setText("N2");

        jLaN3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLaN3.setText("N3");

        jLN4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLN4.setText("N4");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLNomeDisciplina.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLNomeDisciplina.setText("Nome da Disciplina");

        jTFNomeDisciplina.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTFNomeDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeDisciplinaActionPerformed(evt);
            }
        });

        jCDisciplina.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCDisciplina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha uma opção", "Prova", "Trabalho", "Seminário", " " }));

        javax.swing.GroupLayout jPNotasLayout = new javax.swing.GroupLayout(jPNotas);
        jPNotas.setLayout(jPNotasLayout);
        jPNotasLayout.setHorizontalGroup(
            jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNotasLayout.createSequentialGroup()
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLNomeDisciplina))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNotasLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNotasLayout.createSequentialGroup()
                                .addComponent(jLNotas)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNotasLayout.createSequentialGroup()
                                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLN2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLN1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLaN3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLN4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFN1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFN2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFN4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFN3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNotasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCalcular)
                        .addGap(25, 25, 25))))
        );
        jPNotasLayout.setVerticalGroup(
            jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPNotasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addComponent(jLNotas)
                        .addGap(18, 18, 18)
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLN1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLN2))
                        .addGap(18, 18, 18)
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFN4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLaN3))
                        .addGap(18, 18, 18)
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLN4))
                        .addGap(18, 18, 18)
                        .addComponent(jBCalcular))
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLNomeDisciplina)
                        .addGap(18, 18, 18)
                        .addComponent(jTFNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jCDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPAluno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLAluno.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLAluno.setText("Aluno");

        jTFNome.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });

        jTFMatricula.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTFMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFMatriculaActionPerformed(evt);
            }
        });

        jBCadastrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jLMatricula.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLMatricula.setText("Matricula");

        jLNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLNome.setText("Nome");

        javax.swing.GroupLayout jPAlunoLayout = new javax.swing.GroupLayout(jPAluno);
        jPAluno.setLayout(jPAlunoLayout);
        jPAlunoLayout.setHorizontalGroup(
            jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAlunoLayout.createSequentialGroup()
                .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAlunoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBCadastrar)
                            .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addComponent(jTFNome))))
                    .addGroup(jPAlunoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNome)
                            .addComponent(jLMatricula)))
                    .addGroup(jPAlunoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLAluno)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPAlunoLayout.setVerticalGroup(
            jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLMatricula)
                .addGap(18, 18, 18)
                .addComponent(jTFMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jBCadastrar)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFN1ActionPerformed

    private void jTFN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFN2ActionPerformed

    private void jTFN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFN3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFN3ActionPerformed

    private void jTFN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFN4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFN4ActionPerformed

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeActionPerformed

    private void jTFMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFMatriculaActionPerformed

    private void jTFNomeDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeDisciplinaActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
         String nome = jTFNome.getText();
         int matricula = Integer.parseInt(jTFMatricula.getText());
         a = new Aluno(nome, matricula);
         JOptionPane.showMessageDialog(this, a.toString());
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        // TODO add your handling code here:
        Aluno a=new Aluno (jTFNome.getText(),Integer.parseInt(jTFMatricula.getText()));
        TipoAvaliacao tipo =null;
        switch(jCDisciplina.getSelectedIndex()){
            case 1:
            {
                tipo = TipoAvaliacao.PROVA;
                break;
            }
            case 2:
            {
                tipo = TipoAvaliacao.SEMINARIO;
                break;
            }
            case 3:
            {
                tipo = TipoAvaliacao.TRABALHO;
                break;
            
        }
    }//GEN-LAST:event_jBCalcularActionPerformed
    try {
        a.getNotas().add(new Nota(jTFNomeDisciplina.getText(), tipo, Float.parseFloat(jTFN1.getText())));
    }catch (NumberFormatException nfe){
        JOptionPane.showMessageDialog(this,"Você Digitou um Caracter Inválido." +nfe);
        throw new RuntimeException();
    }
    try{
        a.getNotas().add(new Nota (jTFNomeDisciplina.getText(), tipo, Float.parseFloat(jTFN2.getText())));
    }catch (NumberFormatException nfe){
        JOptionPane.showMessageDialog(this, "Você Digitou um Caracter Inválido." +nfe);
        throw new RuntimeException();
    }
    try {
        a.getNotas().add(new Nota (jTFNomeDisciplina.getText(), tipo, Float.parseFloat(jTFN3.getText())));
    }catch (NumberFormatException nfe){
        JOptionPane.showMessageDialog(this, "Você Digitou um Caracter Inválido." +nfe);
    }
    try{ 
        a.getNotas().add (new Nota (jTFNomeDisciplina.getText(), tipo, Float.parseFloat(jTFN4.getText())));
    }catch (NumberFormatException nfe){
        JOptionPane.showMessageDialog(this, "Você Digitou um Caracter Inválido." +nfe);
    }
    JOptionPane.showMessageDialog(null, a.toString()
    + "\n" + "Média: " + a.CalcularMedia());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBCalcular;
    private javax.swing.JComboBox<String> jCDisciplina;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLAluno;
    private javax.swing.JLabel jLMatricula;
    private javax.swing.JLabel jLN1;
    private javax.swing.JLabel jLN2;
    private javax.swing.JLabel jLN4;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLNomeDisciplina;
    private javax.swing.JLabel jLNotas;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLaN3;
    private javax.swing.JPanel jPAluno;
    private javax.swing.JPanel jPNotas;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFMatricula;
    private javax.swing.JTextField jTFN1;
    private javax.swing.JTextField jTFN2;
    private javax.swing.JTextField jTFN3;
    private javax.swing.JTextField jTFN4;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFNomeDisciplina;
    // End of variables declaration//GEN-END:variables
}
